<?php

declare(strict_types=1);

use Risan\Sentiment\Analyzer;
use Risan\Sentiment\Internal\Engine;
use Risan\Sentiment\Internal\RuleBook;
use Risan\Sentiment\Language;

/**
 * Generated by tools/vader-reference/generate.py from the vendored VaderSentiment 3.3.2.
 *
 * @return array{reference: array{negations: list<string>, boosters: array<string, float>, specialCases: array<string, float>}, cases: list<array{text: string, raw: array<string, float>, neg: float, neu: float, pos: float, compound: float}>}
 */
function goldenCorpus(): array
{
    static $golden = null;

    $golden ??= json_decode(
        (string) file_get_contents(__DIR__ . '/../Fixtures/vader-golden.json'),
        true,
        512,
        JSON_THROW_ON_ERROR,
    );

    return $golden;
}

it('carries the reference rule tables', function () {
    $reference = goldenCorpus()['reference'];
    $rules = require dirname(__DIR__, 2) . '/resources/en/rules.php';

    expect(array_map(strval(...), array_keys($rules['negations'])))->toBe($reference['negations']);
    expect($rules['boosters'])->toEqual($reference['boosters']);
    expect($rules['specialCases'])->toEqual($reference['specialCases']);
    expect(array_keys($rules['contrasts']))->toBe(['but']);
});

it('scores every golden text like the reference, raw and rounded', function () {
    $cases = goldenCorpus()['cases'];
    $analyzer = new Analyzer();
    $engine = new Engine(RuleBook::for(Language::English));
    $mismatches = [];

    foreach ($cases as $case) {
        $raw = $engine->polarity($case['text']);
        $result = $analyzer->analyze($case['text']);

        $actual = [
            'raw compound' => $raw['compound'],
            'raw neg' => $raw['negative'],
            'raw neu' => $raw['neutral'],
            'raw pos' => $raw['positive'],
            'compound' => $result->compound,
            'neg' => $result->negative,
            'neu' => $result->neutral,
            'pos' => $result->positive,
        ];
        $expected = [
            'raw compound' => $case['raw']['compound'],
            'raw neg' => $case['raw']['neg'],
            'raw neu' => $case['raw']['neu'],
            'raw pos' => $case['raw']['pos'],
            'compound' => $case['compound'],
            'neg' => $case['neg'],
            'neu' => $case['neu'],
            'pos' => $case['pos'],
        ];

        foreach ($expected as $name => $value) {
            if (abs($actual[$name] - $value) > 1e-9) {
                $mismatches[] = sprintf('%s: expected %s %s, got %s', json_encode($case['text']), $name, $value, $actual[$name]);
            }
        }
    }

    expect(count($cases))->toBeGreaterThan(2000);
    expect(array_slice($mismatches, 0, 10))->toBe([]);
});
