<?php

declare(strict_types=1);

/*
 * Compiles the source data in tools/data into the plain PHP arrays that ship in resources/.
 *
 * Usage: php tools/build-lexicons.php [output-directory]
 *
 * The output is deterministic: running it twice gives identical bytes.
 */

ini_set('serialize_precision', '-1');

const PYTHON_WHITESPACE = " \t\n\r\x0B\f";

const RULE_LISTS = ['negations', 'contrasts', 'phrases', 'dualRole'];

const RULE_MAPS = ['boosters', 'postBoosters', 'specialCases'];

const RULE_FLAGS = ['englishQuirks', 'reduplication'];

const RULE_WORD_LISTS = ['clitics'];

/**
 * Reads vader_lexicon.txt exactly like VADER's make_lex_dict: keys are verbatim
 * (never lower-cased) and the last line wins for a duplicate key.
 *
 * @return array<array-key, float>
 */
function readVaderLexicon(string $path): array
{
    $lexicon = [];

    foreach (readLines($path) as $line) {
        if ($line === '') {
            continue;
        }

        $fields = explode("\t", trim($line, PYTHON_WHITESPACE));

        if (count($fields) < 2) {
            throw new RuntimeException("Malformed lexicon line in {$path}: {$line}");
        }

        $lexicon[$fields[0]] = (float) $fields[1];
    }

    ksort($lexicon, SORT_STRING);

    return $lexicon;
}

/**
 * Keeps single code point emoji only: the reference walks the text code point
 * by code point, so a multi code point key can never match.
 *
 * @return array<string, string>
 */
function readEmojiLexicon(string $path): array
{
    $emoji = [];

    foreach (readLines($path) as $line) {
        $fields = explode("\t", trim($line, PYTHON_WHITESPACE));

        if (count($fields) < 2) {
            throw new RuntimeException("Malformed emoji line in {$path}: {$line}");
        }

        if (mb_strlen($fields[0], 'UTF-8') === 1) {
            $emoji[$fields[0]] = $fields[1];
        }
    }

    return $emoji;
}

/**
 * @return list<string>
 */
function readLines(string $path): array
{
    $contents = file_get_contents($path);

    if ($contents === false) {
        throw new RuntimeException("Cannot read {$path}");
    }

    return explode("\n", rtrim($contents, "\n"));
}

/**
 * Turns the readable rule source (lists of words) into the lookup maps the engine uses.
 *
 * @param array<string, mixed> $source
 *
 * @return array<string, mixed>
 */
function compileRules(array $source, string $path): array
{
    $unknown = array_diff(array_keys($source), RULE_LISTS, RULE_MAPS, RULE_FLAGS, RULE_WORD_LISTS);

    if ($unknown !== []) {
        throw new RuntimeException("Unknown rule keys in {$path}: " . implode(', ', $unknown));
    }

    $compiled = [];

    foreach ($source as $key => $value) {
        if (in_array($key, RULE_FLAGS, true)) {
            if (!is_bool($value)) {
                throw new RuntimeException("{$key} in {$path} must be a bool");
            }

            $compiled[$key] = $value;

            continue;
        }

        if (!is_array($value)) {
            throw new RuntimeException("{$key} in {$path} must be an array");
        }

        if (in_array($key, RULE_MAPS, true)) {
            $numbers = [];

            foreach ($value as $word => $number) {
                if (!is_float($number) && !is_int($number)) {
                    throw new RuntimeException("{$key}['{$word}'] in {$path} must be a number");
                }

                $numbers[(string) $word] = (float) $number;
            }

            $compiled[$key] = $numbers;

            continue;
        }

        foreach ($value as $word) {
            if (!is_string($word) || $word === '') {
                throw new RuntimeException("{$key} in {$path} must hold non-empty strings");
            }
        }

        $compiled[$key] = in_array($key, RULE_WORD_LISTS, true) ? array_values($value) : array_fill_keys($value, true);
    }

    return $compiled;
}

function exportValue(mixed $value, int $depth = 0): string
{
    if (!is_array($value)) {
        return var_export($value, true);
    }

    if ($value === []) {
        return '[]';
    }

    $indent = str_repeat('    ', $depth + 1);
    $isList = array_is_list($value);
    $lines = [];

    foreach ($value as $key => $item) {
        $prefix = $isList ? '' : (is_int($key) ? $key : var_export($key, true)) . ' => ';
        $lines[] = $indent . $prefix . exportValue($item, $depth + 1) . ',';
    }

    return "[\n" . implode("\n", $lines) . "\n" . str_repeat('    ', $depth) . ']';
}

function writeResource(string $path, mixed $data, string $source): void
{
    $directory = dirname($path);

    if (!is_dir($directory) && !mkdir($directory, 0o775, true)) {
        throw new RuntimeException("Cannot create {$directory}");
    }

    $contents = "<?php\n\ndeclare(strict_types=1);\n\n// Generated by tools/build-lexicons.php from {$source}. Do not edit.\n\nreturn "
        . exportValue($data)
        . ";\n";

    if (file_put_contents($path, $contents) === false) {
        throw new RuntimeException("Cannot write {$path}");
    }
}

/**
 * @return array<string, mixed>
 */
function loadRuleSource(string $path): array
{
    $source = require $path;

    if (!is_array($source)) {
        throw new RuntimeException("{$path} must return an array");
    }

    return array_combine(array_map(strval(...), array_keys($source)), $source);
}

$root = dirname(__DIR__);
$output = $argv[1] ?? $root . '/resources';

writeResource(
    $output . '/en/lexicon.php',
    readVaderLexicon($root . '/tools/data/en/vader_lexicon.txt'),
    'tools/data/en/vader_lexicon.txt',
);
writeResource(
    $output . '/en/emoji.php',
    readEmojiLexicon($root . '/tools/data/en/emoji_utf8_lexicon.txt'),
    'tools/data/en/emoji_utf8_lexicon.txt',
);
writeResource(
    $output . '/en/rules.php',
    compileRules(loadRuleSource($root . '/tools/data/en/rules.php'), 'tools/data/en/rules.php'),
    'tools/data/en/rules.php',
);
